"""
    check_errs(f, ∇f, Ȳ::AS, X::AS, V::AS, ε_abs::Real=1e-10, ε_rel::Real=1e-7)::Bool
"""
check_errs(f, ∇f, Ȳ::AS, X::AS, V::AS, ε_abs::Real=1e-7, ε_rel::Real=1e-5)::Bool =
    assert_approx_equal(
        central_fdm(2, 1)(ϵ->sum(Ȳ .* f(X .+ ϵ .* V))),
        sum(∇f(f(X), Ȳ, X) .* V),
        ε_abs, ε_rel)

"""
    repeatedly_check_errs(N::Int, f, ∇f, Ȳ, X, V, ε_abs=1e-10, ε_rel=1e-7)::Bool

Call check_errs `N` times with arguments generated by 0-ary functions `Ȳ`, `X` and `V`.
"""
repeatedly_check_errs(N::Int, f, ∇f, Ȳ, X, V, ε_abs=1e-7, ε_rel=1e-5)::Bool =
    all(map(n->check_errs(f, ∇f, Ȳ(), X(), V(), ε_abs, ε_rel), 1:N))
